### ISSUE TITLE
Warning chrome extension store

### ISSUE THREAD

**Issue by webysther** [ArchiveBox/archivebox-browser-extension#28]
When access the google chrome extension page: "This extension may end soon because it does not follow Chrome extension best practices."

https://support.google.com/chrome_webstore/answer/2664769#unsupported_extensions

**Comment by tjhorner** [comment]
This is because the extension still uses MV2. The upgrade to MV3 is tracked in #23; once that is complete, the warning will go away.

For now you can ignore it though. Thanks for the heads up.
